title: San Francisco Street Fair Coalition
email: sfstreetfaircoalition@gmail.com
description: "The San Francisco Street Fair Coalition (SFSFC) is a vibrant network of individuals and organizations dedicated to fostering San Francisco's unique street fair culture. Imagine a tapestry woven from the diverse threads of community-driven celebrations, artistic expression, culinary delights, and grassroots activism, all converging in the heart of the city's streets."
baseurl: ""
url: "https://sfstreetfaircoalition.org"
image: images/alllogos.png

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
